export { default as emplRegisterRoute } from './emplRegisterRoute'
export { default as emplUpdateRoute } from './emplUpdateRoute'
export { default as emplDeletionRoute } from './emplDeletionRoute'
export { default as emplGetOneRoute } from './emplGetOneRoute'
export { default as emplGetAllRoute } from './emplGetAllRoute'
